// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5RDQmKzirATcmK6QZ0asZBPqBzcvbO5U',
    appId: '1:355588618342:web:4b429809be9ba289e255a7',
    messagingSenderId: '355588618342',
    projectId: 'mingrr',
    authDomain: 'mingrr.firebaseapp.com',
    storageBucket: 'mingrr.firebasestorage.app',
    measurementId: 'G-2EMYC6SME2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2yPNjvVCxq2rx209085EqfL8fNbGn5mQ',
    appId: '1:355588618342:android:ee38434c08c8871be255a7',
    messagingSenderId: '355588618342',
    projectId: 'mingrr',
    storageBucket: 'mingrr.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwSXdq79AdCNd5eqyOrR20y_X60uspUZI',
    appId: '1:355588618342:ios:d5abaa8336c6683fe255a7',
    messagingSenderId: '355588618342',
    projectId: 'mingrr',
    storageBucket: 'mingrr.firebasestorage.app',
    iosBundleId: 'com.mingrr.mingrr',
  );
}
